# Windows-specific settings for IoT client
# This file contains Windows-optimized configuration values

robot_name: "drone_1"
input_topic: "{robot_name}/topic"
base_path: "certifications"
input_cert: "{base_path}\\{robot_name}\\{robot_name}.cert.pem"
input_key: "{base_path}\\{robot_name}\\{robot_name}.private.key"
aws_access_key_id: ""
aws_secret_access_key: ""
input_ca: "AmazonRootCA1.pem"
input_endpoint: "a1qlex7vqi1791-ats.iot.us-east-1.amazonaws.com"
input_clientId: "arn:aws:iot:us-east-1:111964674713:thing/{robot_name}"
session_key: "hkiitshow"
simulator_endpoint: "https://humanoid-robot-simulator-74gfpibg5q-uc.a.run.app"

# Windows-specific settings
windows:
  # Connection timeout in seconds (higher for Windows stability)
  connection_timeout: 15
  # Maximum retry attempts
  max_retry_attempts: 5
  # Enable WebSocket fallback
  websocket_fallback: true
  # Log level (DEBUG, INFO, WARNING, ERROR)
  log_level: "INFO"
  # Enable file logging
  file_logging: true
  # Log file path (relative to IoT directory)
  log_file: "logs\\iot_client.log"
  # Request timeout for local robot commands
  request_timeout: 2.0
  # Sleep interval for action monitoring
  sleep_interval: 0.2
