robot_name: "drone_1"
input_topic: "{robot_name}/topic"
base_path: "certificates"
input_cert: "{base_path}/{robot_name}/{robot_name}.cert.pem"
input_key: "{base_path}/{robot_name}/{robot_name}.private.key"
aws_access_key_id: ""
aws_secret_access_key: ""
input_ca: "AmazonRootCA1.pem"
input_endpoint: "a1qlex7vqi1791-ats.iot.us-east-1.amazonaws.com"
input_clientId: "arn:aws:iot:us-east-1:111964674713:thing/{robot_name}"
session_key: "hkiitshow"
simulator_endpoint: "https://humanoid-robot-simulator-74gfpibg5q-uc.a.run.app"
