# Drone Controller Configuration

# Default drone settings
drones:
  default:
    connection_timeout: 10.0
    command_timeout: 5.0
    max_speed: 50
    video_enabled: false
    
  # Example drone configurations
  # Uncomment and modify IP addresses as needed
  # drone_001:
  #   ip_address: "192.168.10.1"
  #   video_enabled: true
  #   max_speed: 40
  #   
  # drone_002:
  #   ip_address: "192.168.10.2" 
  #   video_enabled: true
  #   max_speed: 40
  #
  # drone_003:
  #   ip_address: "192.168.10.3"
  #   video_enabled: false
  #   max_speed: 45

# Swarm configuration
swarms:
  default:
    max_drones: 10
    takeoff_stagger_delay: 1.0
    landing_stagger_delay: 0.5
    
  demo_swarm:
    max_drones: 5
    takeoff_stagger_delay: 2.0
    landing_stagger_delay: 1.0

# Formation presets
formations:
  line:
    spacing: 150
    orientation: 0
    
  circle:
    radius: 200
    
  diamond:
    size: 200
    
  v_formation:
    spacing: 150
    angle: 45
    
  grid_2x2:
    rows: 2
    cols: 2
    spacing: 150
    
  # Custom formation example
  triangle:
    type: custom
    positions:
      - {x: 0, y: 100, z: 150}
      - {x: -87, y: -50, z: 150}
      - {x: 87, y: -50, z: 150}

# Safety parameters
safety:
  min_distance: 100          # Minimum distance between drones (cm)
  collision_threshold: 80    # Distance threshold for collision warnings (cm)
  max_altitude: 300          # Maximum flight altitude (cm)
  battery_warning_threshold: 20    # Battery level to issue warnings (%)
  battery_critical_threshold: 10   # Battery level for emergency landing (%)
  emergency_land_on_signal_loss: true

# Logging configuration
logging:
  level: "INFO"              # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  log_directory: "logs"
  
# Mission parameters
missions:
  default_mission_timeout: 300    # Default mission timeout (seconds)
  waypoint_tolerance: 30          # Distance tolerance for waypoint achievement (cm)
  formation_hold_time: 5          # Time to hold formation before next command (seconds)
