# Drone Controller Configuration

# Default drone settings
drones:
  default:
    connection_timeout: 10.0
    command_timeout: 5.0
    max_speed: 50
    video_enabled: false

  # Example drone configurations
  # Uncomment and modify IP addresses as needed
  drone_001:
    ip_address: "127.0.0.1"  # Localhost for simulator
    video_enabled: true
    max_speed: 40

  drone_002:
    ip_address: "127.0.0.1"  # Localhost for simulator
    video_enabled: true
    max_speed: 40

  drone_003:
    ip_address: "127.0.0.1"  # Localhost for simulator
    video_enabled: false
    max_speed: 45

# Swarm configuration
swarms:
  default:
    max_drones: 10
    takeoff_stagger_delay: 1.0
    synchronized_takeoff: true    # Enable synchronized takeoff for swarm mode
    landing_stagger_delay: 0.0   # 0 for simultaneous landing
    synchronized_landing: true   # Enable synchronized landing
    command_timeout: 15.0        # Timeout for next command after takeoff (seconds)

  demo_swarm:
    max_drones: 5
    takeoff_stagger_delay: 2.0
    synchronized_takeoff: true    # Enable synchronized takeoff for swarm mode
    landing_stagger_delay: 0.0   # 0 for simultaneous landing
    synchronized_landing: true   # Enable synchronized landing
    command_timeout: 15.0        # Timeout for next command after takeoff (seconds)

# Formation presets
formations:
  line:
    spacing: 150
    orientation: 0

  circle:
    radius: 200

  diamond:
    size: 200

  v_formation:
    spacing: 150
    angle: 45

  grid_2x2:
    rows: 2
    cols: 2
    spacing: 150

  # Custom formation example
  triangle:
    type: custom
    positions:
      - {x: 0, y: 100, z: 150}
      - {x: -87, y: -50, z: 150}
      - {x: 87, y: -50, z: 150}

# Safety parameters
safety:
  min_distance: 100          # Minimum distance between drones (cm)
  collision_threshold: 80    # Distance threshold for collision warnings (cm)
  max_altitude: 300          # Maximum flight altitude (cm)
  battery_warning_threshold: 20    # Battery level to issue warnings (%)
  battery_critical_threshold: 10   # Battery level for emergency landing (%)
  emergency_land_on_signal_loss: true

# Error handling configuration
error_handling:
  motor_stop:
    max_retries: 5                    # Maximum retry attempts for motor stop errors
    base_delay: 2.0                   # Base delay between retries (seconds)
    backoff_multiplier: 1.5           # Exponential backoff multiplier
    max_delay: 10.0                   # Maximum delay between retries (seconds)
    enable_degraded_mode: true        # Enable degraded performance mode
    auto_exclude_problematic_drones: true  # Automatically exclude problematic drones
    cooldown_period: 30.0             # Cooldown period before re-enabling drone (seconds)

  connection_timeout:
    max_retries: 3
    base_delay: 1.0
    backoff_multiplier: 2.0

  movement_timeout:
    max_retries: 3
    base_delay: 0.5
    backoff_multiplier: 1.5

# Retry configuration
retry_config:
  default_max_retries: 3
  default_base_delay: 1.0
  default_backoff_multiplier: 1.5
  enable_exponential_backoff: true
  enable_jitter: true
  jitter_max_ms: 1000

# Degraded performance mode
degraded_performance:
  enable_auto_mode: true              # Automatically enter degraded mode
  reduced_speed_factor: 0.7           # Speed reduction factor (70% of normal)
  reduced_movement_distance: 0.8      # Movement distance reduction factor
  extended_delays: true               # Use extended delays between commands
  skip_non_critical_operations: true  # Skip non-critical operations
  battery_threshold_for_degraded_mode: 30  # Battery level to trigger degraded mode (%)

# Logging configuration
logging:
  level: "INFO"              # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true
  log_directory: "logs"

# Mission parameters
missions:
  default_mission_timeout: 600          # Increased default mission timeout (seconds)
  waypoint_tolerance: 30                # Distance tolerance for waypoint achievement (cm)
  formation_hold_time: 10               # Increased time to hold formation before next command (seconds)
  command_completion_timeout: 30        # Time to wait for command completion before considering timeout
